# Paths
obsidian_posts_folder: "/home/user/Documents/Vault/Posts"
obsidian_images_folder: "/home/user/Documents/Vault/Images"
jekyll_posts_folder: "/home/user/Documents/Blog/_posts"
jekyll_images_folder: "/home/user/Documents/Blog/assets/images"
